name: ubuntu-lint

on:
  pull_request:

  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  ubuntu_lint:
    name: Lint
    runs-on: ubuntu-22.04
    env:
      RUBYOPT: -Ilib
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup ruby
        uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Run Lint
        run: bundle exec rake rubocop
      - name: Check manifest
        run: bundle exec rake check_manifest
    timeout-minutes: 15
