name: ubuntu-lint

on:
  pull_request:

  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  ubuntu_lint:
    name: Lint
    runs-on: ubuntu-22.04
    env:
      RUBYOPT: -Ilib
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup ruby
        uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1.319.0
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Run Lint
        run: bundle exec rake rubocop
      - name: Check manifest
        run: bundle exec rake check_manifest
    timeout-minutes: 15
